# data cleaning

In [1]:
import pandas as pd

In [19]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
cd C:\Users\dell\OneDrive\Desktop\Finger Tips\Machine learning\Data set

C:\Users\dell\OneDrive\Desktop\Finger Tips\Machine learning\Data set

In [4]:
data = pd.read_excel("ML Live Flight Fare Resourses16963295320 (1).xlsx")

In [5]:
data.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [7]:
data.shape

(10683, 11)

In [8]:
data.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [9]:
data.drop(["Additional_Info","Route"],axis =1,inplace= True)

In [10]:
data.head(2)

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,22:20,01:10 22 Mar,2h 50m,non-stop,3897
1,Air India,1/05/2019,Kolkata,Banglore,05:50,13:15,7h 25m,2 stops,7662

In [12]:
data[data["Total_Stops"].isnull()==True]

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Price
9039,Air India,6/05/2019,Delhi,Cochin,09:45,09:25 07 May,23h 40m,NaN,7480

In [14]:
data.dropna(inplace=True,ignore_index=True)

In [16]:
data.drop_duplicates(inplace=True,ignore_index=True)

In [21]:
data["Date_of_Journey"]=pd.to_datetime(data["Date_of_Journey"])

In [23]:
data["Day"]=data["Date_of_Journey"].dt.day

In [24]:
data["month"]=data["Date_of_Journey"].dt.month

In [25]:
data["year"]=data["Date_of_Journey"].dt.year

In [26]:
data.drop("Date_of_Journey",axis =1,inplace = True)

In [27]:
data.drop("year",axis =1,inplace = True)

In [28]:
data["dep_hour"]=pd.to_datetime(data["Dep_Time"]).dt.hour

In [30]:
data["dep_min"]=pd.to_datetime(data["Dep_Time"]).dt.minute

In [31]:
data.drop("Dep_Time",axis=1,inplace =True)

In [33]:
data["Arrival_hour"]=pd.to_datetime(data["Arrival_Time"]).dt.hour

In [34]:
data["Arrival_min"]=pd.to_datetime(data["Arrival_Time"]).dt.minute

In [35]:
data.drop("Arrival_Time",axis=1,inplace=True)

In [36]:
data.head()

,Airline,Source,Destination,Duration,Total_Stops,Price,Day,month,dep_hour,dep_min,Arrival_hour,Arrival_min
0,IndiGo,Banglore,New Delhi,2h 50m,non-stop,3897,24,3,22,20,1,10
1,Air India,Kolkata,Banglore,7h 25m,2 stops,7662,1,5,5,50,13,15
2,Jet Airways,Delhi,Cochin,19h,2 stops,13882,9,6,9,25,4,25
3,IndiGo,Kolkata,Banglore,5h 25m,1 stop,6218,12,5,18,5,23,30
4,IndiGo,Banglore,New Delhi,4h 45m,1 stop,13302,1,3,16,50,21,35

In [52]:
data["Duration"].str.split().str[1]

0        50m
1        25m
2        NaN
3        25m
4        45m
        ...
10457    30m
10458    35m
10459    NaN
10460    40m
10461    20m
Name: Duration, Length: 10462, dtype: object

In [58]:
data["Duration_hour"]=data["Duration"].str.split().str[0]

In [70]:
data["Duration_min"]=data["Duration"].str.split().str[1]

In [71]:
data[["Duration_min","Duration_hour"]]=data[["Duration_min","Duration_hour"]].fillna(0)

In [72]:
data.head()

,Airline,Source,Destination,Duration,Total_Stops,Price,Day,month,dep_hour,dep_min,Arrival_hour,Arrival_min,Duration_hour,Duration_min
0,IndiGo,Banglore,New Delhi,2h 50m,non-stop,3897,24,3,22,20,1,10,2h,50m
1,Air India,Kolkata,Banglore,7h 25m,2 stops,7662,1,5,5,50,13,15,7h,25m
2,Jet Airways,Delhi,Cochin,19h,2 stops,13882,9,6,9,25,4,25,19h,0
3,IndiGo,Kolkata,Banglore,5h 25m,1 stop,6218,12,5,18,5,23,30,5h,25m
4,IndiGo,Banglore,New Delhi,4h 45m,1 stop,13302,1,3,16,50,21,35,4h,45m

In [75]:
data[["Duration_hour","Duration_min"]]=data[["Duration_hour","Duration_min"]].replace("[h-m]","",regex=True)

In [78]:
data[["Duration_hour","Duration_min"]]=data[["Duration_hour","Duration_min"]].astype(int)

In [81]:
data.drop("Duration",axis=1,inplace=True)

In [82]:
data.head()

,Airline,Source,Destination,Total_Stops,Price,Day,month,dep_hour,dep_min,Arrival_hour,Arrival_min,Duration_hour,Duration_min
0,IndiGo,Banglore,New Delhi,non-stop,3897,24,3,22,20,1,10,2,50
1,Air India,Kolkata,Banglore,2 stops,7662,1,5,5,50,13,15,7,25
2,Jet Airways,Delhi,Cochin,2 stops,13882,9,6,9,25,4,25,19,0
3,IndiGo,Kolkata,Banglore,1 stop,6218,12,5,18,5,23,30,5,25
4,IndiGo,Banglore,New Delhi,1 stop,13302,1,3,16,50,21,35,4,45

In [83]:
data.head()

,Airline,Source,Destination,Total_Stops,Price,Day,month,dep_hour,dep_min,Arrival_hour,Arrival_min,Duration_hour,Duration_min
0,IndiGo,Banglore,New Delhi,non-stop,3897,24,3,22,20,1,10,2,50
1,Air India,Kolkata,Banglore,2 stops,7662,1,5,5,50,13,15,7,25
2,Jet Airways,Delhi,Cochin,2 stops,13882,9,6,9,25,4,25,19,0
3,IndiGo,Kolkata,Banglore,1 stop,6218,12,5,18,5,23,30,5,25
4,IndiGo,Banglore,New Delhi,1 stop,13302,1,3,16,50,21,35,4,45

In [84]:
data.groupby("Airline")["Price"].mean()

Airline
Air Asia                              5590.260188
Air India                             9556.608028
GoAir                                 5861.056701
IndiGo                                5668.469897
Jet Airways                          11599.021081
Jet Airways Business                 58358.666667
Multiple carriers                    10902.678094
Multiple carriers Premium economy    11418.846154
SpiceJet                              4335.841718
Trujet                                4140.000000
Vistara                               7801.355649
Vistara Premium economy               8962.333333
Name: Price, dtype: float64

In [87]:
Airline = pd.get_dummies(data["Airline"])

In [89]:
Source=pd.get_dummies(data["Source"])

In [90]:
Destination =pd.get_dummies(data["Destination"])

In [91]:
data["Total_Stops"].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', '4 stops'],
      dtype=object)

In [93]:
data["Total_Stops"]=data["Total_Stops"].replace(['non-stop', '2 stops', '1 stop', '3 stops', '4 stops'],[0,2,1,3,4])

In [95]:
data.drop(["Airline","Source","Destination"],axis=True,inplace=True)

In [98]:
data=pd.concat([data,Airline,Source,Destination],axis=1)

In [99]:
data.head()

,Total_Stops,Price,Day,month,dep_hour,dep_min,Arrival_hour,Arrival_min,Duration_hour,Duration_min,...,Chennai,Delhi,Kolkata,Mumbai,Banglore,Cochin,Delhi,Hyderabad,Kolkata,New Delhi
0,0,3897,24,3,22,20,1,10,2,50,...,False,False,False,False,False,False,False,False,False,True
1,2,7662,1,5,5,50,13,15,7,25,...,False,False,True,False,True,False,False,False,False,False
2,2,13882,9,6,9,25,4,25,19,0,...,False,True,False,False,False,True,False,False,False,False
3,1,6218,12,5,18,5,23,30,5,25,...,False,False,True,False,True,False,False,False,False,False
4,1,13302,1,3,16,50,21,35,4,45,...,False,False,False,False,False,False,False,False,False,True

In [100]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10462 entries, 0 to 10461
Data columns (total 33 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Total_Stops                        10462 non-null  int64
 1   Price                              10462 non-null  int64
 2   Day                                10462 non-null  int32
 3   month                              10462 non-null  int32
 4   dep_hour                           10462 non-null  int32
 5   dep_min                            10462 non-null  int32
 6   Arrival_hour                       10462 non-null  int32
 7   Arrival_min                        10462 non-null  int32
 8   Duration_hour                      10462 non-null  int64
 9   Duration_min                       10462 non-null  int64
 10  Air Asia                           10462 non-null  bool
 11  Air India                          10462 non-null  bool
 12  GoAir                              10462 non-null  bool
 13  IndiGo                             10462 non-null  bool
 14  Jet Airways                        10462 non-null  bool
 15  Jet Airways Business               10462 non-null  bool
 16  Multiple carriers                  10462 non-null  bool
 17  Multiple carriers Premium economy  10462 non-null  bool
 18  SpiceJet                           10462 non-null  bool
 19  Trujet                             10462 non-null  bool
 20  Vistara                            10462 non-null  bool
 21  Vistara Premium economy            10462 non-null  bool
 22  Banglore                           10462 non-null  bool
 23  Chennai                            10462 non-null  bool
 24  Delhi                              10462 non-null  bool
 25  Kolkata                            10462 non-null  bool
 26  Mumbai                             10462 non-null  bool
 27  Banglore                           10462 non-null  bool
 28  Cochin                             10462 non-null  bool
 29  Delhi                              10462 non-null  bool
 30  Hyderabad                          10462 non-null  bool
 31  Kolkata                            10462 non-null  bool
 32  New Delhi                          10462 non-null  bool
dtypes: bool(23), int32(6), int64(4)
memory usage: 807.3 KB

# Multiple linear Regression

In [101]:
x = data.drop("Price",axis=1)
y=data["Price"]

In [102]:
from sklearn.model_selection import train_test_split

In [135]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=40)

In [136]:
from sklearn.linear_model import LinearRegression

In [137]:
model = LinearRegression()

In [138]:
model.fit(x_train,y_train)

LinearRegression()

In [139]:
yp = model.predict(x_test)

In [140]:
from sklearn.metrics import r2_score,root_mean_squared_error

In [141]:
r2_score(y_test,yp)

0.6433930243021673

In [142]:
root_mean_squared_error(y_test,yp)

2700.1304318649677

# Lasso

In [143]:
from sklearn.linear_model import Lasso

In [144]:
model1 = Lasso()

In [145]:
model1.fit(x_train,y_train)

Lasso()

In [146]:
y_predict=model1.predict(x_test)

In [147]:
r2_score(y_test,y_predict)

0.6434413727233427

In [148]:
root_mean_squared_error(y_test,y_predict)

2699.9473851533144

# all model

In [161]:
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor

In [162]:
a = [SVC,DecisionTreeRegressor,RandomForestRegressor,KNeighborsRegressor]

In [164]:
for i in a:
    model = i()
    model.fit(x_train,y_train)
    print(i,"Training Accuracy:",model.score(x_train,y_train))
    print(i,"Testing Accuracy:",model.score(x_test,y_test))

<class 'sklearn.svm._classes.SVC'> Training Accuracy: 0.14243039789700085
<class 'sklearn.svm._classes.SVC'> Testing Accuracy: 0.11132345914954611
<class 'sklearn.tree._classes.DecisionTreeRegressor'> Training Accuracy: 0.9705080084730793
<class 'sklearn.tree._classes.DecisionTreeRegressor'> Testing Accuracy: 0.6545894626790396
<class 'sklearn.ensemble._forest.RandomForestRegressor'> Training Accuracy: 0.9546706783331502
<class 'sklearn.ensemble._forest.RandomForestRegressor'> Testing Accuracy: 0.7812026359495234
<class 'sklearn.neighbors._regression.KNeighborsRegressor'> Training Accuracy: 0.717794115554981
<class 'sklearn.neighbors._regression.KNeighborsRegressor'> Testing Accuracy: 0.581770582932833