# Questions

In [ ]:
1) Load the given dataset 
2) Print all the column names 
3) Describe the data 
4) Drop address, date, postcode, YearBuilt, lattitude, longtitude columns 
5) Find the count of null value in each column 
6) Fill the null value of property count, distance, Bedroom2, Bathroom, Car with 0
7) Fill Null value of land size and bidding area columns with Mean 
8) Find the unique value in method column 
9) Create a dummy data for categorical data 

model 

1) Create the target data and feature data where target data is price 
2) Create a linear regression model for Target and feature data 
3) Check if the model is overfitting or underfitting or it is accurate 
4) If the model is overfitting then apply ridge and lasso regression algorithms 
5) Extract slope and intercept value from the model 
6) Display Mean Squared Error 
7) Display Mean Absolute Error 
8) Display Root mean Squared error 
9) Display R2 score

# 1) Load the given dataset

In [3]:
import pandas as pd

In [4]:
import warnings
warnings.filterwarnings("ignore")

In [5]:
cd C:\Users\dell\OneDrive\Desktop\Finger Tips\Machine learning\Projects\Projects datafile

C:\Users\dell\OneDrive\Desktop\Finger Tips\Machine learning\Projects\Projects datafile

In [6]:
df = pd.read_csv("ML Linear Regression Home Price Prediction & Analysis Project.txt")

# 2) Print all the column names

In [8]:
pd.set_option("display.max_columns",None)

In [47]:
df.head(2)

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.0,160.25,Yarra City Council,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.0,160.25,Yarra City Council,Northern Metropolitan,4019.0

# 3) Describe the data

In [12]:
df.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,34857.000000,2.724700e+04,34856.000000,34856.000000,26640.000000,26631.000000,26129.000000,23047.000000,13742.00000,15551.000000,26881.000000,26881.000000,34854.000000
mean,3.031012,1.050173e+06,11.184929,3116.062859,3.084647,1.624798,1.728845,593.598993,160.25640,1965.289885,-37.810634,145.001851,7572.888306
std,0.969933,6.414671e+05,6.788892,109.023903,0.980690,0.724212,1.010771,3398.841946,401.26706,37.328178,0.090279,0.120169,4428.090313
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1196.000000,-38.190430,144.423790,83.000000
25%,2.000000,6.350000e+05,6.400000,3051.000000,2.000000,1.000000,1.000000,224.000000,102.00000,1940.000000,-37.862950,144.933500,4385.000000
50%,3.000000,8.700000e+05,10.300000,3103.000000,3.000000,2.000000,2.000000,521.000000,136.00000,1970.000000,-37.807600,145.007800,6763.000000
75%,4.000000,1.295000e+06,14.000000,3156.000000,4.000000,2.000000,2.000000,670.000000,188.00000,2000.000000,-37.754100,145.071900,10412.000000
max,16.000000,1.120000e+07,48.100000,3978.000000,30.000000,12.000000,26.000000,433014.000000,44515.00000,2106.000000,-37.390200,145.526350,21650.000000

# 4) Drop address, date, postcode, YearBuilt, lattitude, longtitude columns

In [15]:
df.drop( [ "Address" , "Date" , "Postcode" , "YearBuilt" , "Lattitude" , "Longtitude" ] , axis = 1 , inplace = True )

# 5) Find the count of null value in each column

In [53]:
df.isnull().sum()

Suburb              0
Rooms               0
Type                0
Price            7610
Method              0
SellerG             0
Distance            0
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
CouncilArea         0
Regionname          0
Propertycount       0
dtype: int64

In [17]:
# (Price = 7610, Distance = 1, Bedroom2 = 8217, Bathroom = 8226 , Car = 8728 ,
#  Landsize = 11810 ,BuildingArea = 21115, CouncilArea = 3, Regionname = 3, Propertycount = 3 )

# 6) Fill the null value of property count, distance, Bedroom2, Bathroom, Car with 0

In [33]:
fill = {"Propertycount": 0 , "Distance": 0 ,"Bedroom2": 0 ,"Bathroom": 0 ,"Car": 0 }

In [38]:
df.fillna(fill,inplace=True)

# 7) Fill Null value of land size and bidding area columns with Mean

In [21]:
df["Landsize"].mean()

np.float64(593.598993361392)

In [23]:
df["BuildingArea"].mean()

np.float64(160.2564003565711)

In [43]:
df["CouncilArea"].mode()

0    Boroondara City Council
Name: CouncilArea, dtype: object

In [49]:
df["Regionname"].mode()

0    Southern Metropolitan
Name: Regionname, dtype: object

In [51]:
fill1 = {"Landsize":593.59,"BuildingArea":160.25,"CouncilArea":"Boroondara City Council","Regionname":"Southern Metropolitan"}

In [52]:
df.fillna(fill1,inplace=True)

# 8) Find the unique value in method column

In [27]:
df["Method"].unique()

array(['SS', 'S', 'VB', 'SP', 'PI', 'SN', 'W', 'PN', 'SA'], dtype=object)

# 9) Create a dummy data for categorical data

In [78]:
df.info()

In [ ]:
#(label encoder = "Suburb","Method","SellerG","CouncilArea","Regionname")

In [55]:
df["Suburb"].unique()

In [57]:
df["Type"].unique()

In [59]:
df["Method"].unique()

In [61]:
df["SellerG"].unique()

In [63]:
df["CouncilArea"].unique()

In [65]:
df["Regionname"].unique()

Label encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
encoder = LabelEncoder()

In [71]:
df["Suburb"] = encoder.fit_transform(df["Suburb"])

In [72]:
df["Method"] = encoder.fit_transform(df["Method"])

In [73]:
df["SellerG"] = encoder.fit_transform(df["SellerG"])

In [74]:
df["CouncilArea"] = encoder.fit_transform(df["CouncilArea"])

In [75]:
df["Regionname"] = encoder.fit_transform(df["Regionname"])

In [76]:
df["Type"] = encoder.fit_transform(df["Type"])

# Z - score

In [ ]:
# sir, in this outliar find methods in  we want IQR method apply but Q3 and Q1 find "nan" so how can this apply ?

In [80]:
# z-score = (x-mean)/std

In [83]:
mean = df["Price"].mean()

In [84]:
std = df["Price"].std()

In [86]:
df["z-score"] = (df["Price"]-mean)/std

In [89]:
df[(df["z-score"]>-3)|(df["z-score"]<3)]

In [92]:
df["Price"]=df["Price"].fillna(1050210)

In [101]:
df.drop("z-score",axis = 1,inplace=True)

# 1) Create the target data and feature data where target data is price

In [102]:
x = df.drop("Price",axis=1)
y = df["Price"]

In [103]:
from sklearn.model_selection import train_test_split

In [104]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2,random_state=42)

# 2) Create a linear regression model for Target and feature data

In [105]:
from sklearn.linear_model import LinearRegression

In [106]:
model = LinearRegression()

In [107]:
model.fit(x_train,y_train)

LinearRegression()

# 3) Check if the model is overfitting or underfitting or it is accurate

In [108]:
model.score(x_train,y_train)

0.3284700671598503

In [109]:
model.score(x_test,y_test)

0.16678012869464232

# 5) Extract slope and intercept value from the model

In [110]:
model.intercept_

np.float64(846033.3419906751)

In [111]:
model.coef_

array([-5.01673726e+02,  2.08722810e+05, -1.46220877e+05, -1.20424232e+03,
       -1.05407742e+02, -2.82607440e+04, -8.29583974e+04,  1.53783465e+05,
        1.67087062e+04,  4.91336171e+00,  4.07223661e+02, -3.52358128e+03,
        9.76627460e+03,  4.37318367e-01])

# 6) Display Mean Squared Error

In [113]:
yp = model.predict(x_test)

In [112]:
from sklearn.metrics import root_mean_squared_error,r2_score,mean_absolute_error,mean_squared_error

In [114]:
mean_squared_error(y_test,yp)

246747926437.0155

# 7) Display Mean Absolute Error

In [115]:
mean_absolute_error(y_test,yp)

312087.18992577575

# 8) Display Root mean Squared error

In [116]:
root_mean_squared_error(y_test,yp)

496737.2811024108

#  9) Display R2 score

In [117]:
r2_score(y_test,yp)

0.16678012869464232

# Lasso

In [119]:
from sklearn.linear_model import Lasso

In [120]:
model1 = Lasso()

In [121]:
model1.fit(x_train,y_train)

Lasso()

In [122]:
yp1=model1.predict(x_test)

In [123]:
r2_score(y_test,yp)

0.16678012869464232

In [124]:
root_mean_squared_error(y_test,yp)

496737.2811024108

# Random Forest

In [125]:
from sklearn.ensemble import RandomForestRegressor

In [131]:
model2 = RandomForestRegressor()

In [132]:
model2.fit(x_train,y_train)

RandomForestRegressor()

In [133]:
model2.score(x_train,y_train)

0.9227454558413042

In [134]:
model2.score(x_test,y_test)

0.493229246204699